#!/system/xbin/ash
#
# Load cifs and ext4 kernel modules

if [ ! -f /proc/config.gz ]; then

#insmod /system/lib/modules/slow-work.ko
busybox insmod /system/lib/modules/nls_utf8.ko
busybox insmod /system/lib/modules/cifs-stock.ko

busybox insmod /system/lib/modules/jbd2.ko
busybox insmod /system/lib/modules/ext4.ko

else

  # on custom kernel, only load cifs

  busybox insmod /system/lib/modules/cifs-2ndboot.ko

fi
