#!/system/bin/sh
#
# load multitouch module

# Module location
MODULE="/system/lib/modules/multitouch.ko"

# Max number of fingers
MAX_TOUCH=`getprop persist.sys.multitouch`
if [ -z "$MAX_TOUCH" ]; then
    MAX_TOUCH=2
fi

# Dont load if on custom kernel
if [ ! -f /proc/config.gz ]; then

# Load the module
insmod $MODULE touch_num=$MAX_TOUCH

fi
